---
- hosts: all
  vars:
    user: trawick
    remote_checkout: /home/trawick/git/edurepo
    static_dir: /home/trawick/edurepo-static
    log_dir: /var/log/django-edurepo
    log_group: edurepo-loggers
    log_dir_owner: www-data
    python_binary: /home/trawick/python-2.7/bin/python
  remote_user: trawick
  tasks:
    - name: Check that the server is alive
      action: ping
    - name: Create log directory
      command: /usr/bin/sudo mkdir {{ log_dir }} creates={{ log_dir }}
    - name: Fix owner/group on log directory
      command: /usr/bin/sudo chown {{ log_dir_owner }}:{{ log_group }} {{ log_dir }}
    - name: Fix permissions on log directory
      command: /usr/bin/sudo chmod 0775 {{ log_dir }}
    - name: Fix group sticky on log directory
      command: /usr/bin/sudo chmod g+s {{ log_dir }}
    - git: repo=git://github.com/trawick/edurepo.git
           dest={{ remote_checkout }}
           version=HEAD
           update=yes
           force=no
    - name: Overlay files that don't live in git
      command: 'cp -pR /home/trawick/edurepo-overlays/src {{ remote_checkout }}'
    - file: >
           dest={{ remote_checkout }}/envs
           mode=755
           owner={{ user }}
           group={{ user }}
           state=directory
    - name: Create new virtualenv
      command: /usr/local/bin/virtualenv -p {{ python_binary }} {{ remote_checkout }}/envs/edurepo creates={{ remote_checkout }}/envs/edurepo
    - file: >
           dest={{ static_dir }}
           mode=755
           owner={{ user }}
           group={{ user }}
           state=directory
    - pip: virtualenv={{ remote_checkout }}/envs/edurepo
           requirements={{ remote_checkout }}/src/requirements.txt
    - django_manage: >
          app_path={{ remote_checkout }}/src/edurepo
          command=collectstatic
          virtualenv={{ remote_checkout }}/envs/edurepo
    - django_manage: >
          app_path={{ remote_checkout }}/src/edurepo
          command=syncdb
          virtualenv={{ remote_checkout }}/envs/edurepo
    - name: Restart httpd
      command: '/usr/bin/sudo /usr/local/bin/apachectl graceful'
